name: Build and Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt \
            --target=".python_packages/lib/site-packages"
      
      - name: Compress files
        run: zip -r release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'crewing-data-ext'
          slot-name: 'Production'
          package: 'release.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_39F604975B334051B9B1032DBFD280BE }}
